launcher_args: {experiment_name: canopus_contrastive_mist,
  script_name: src/mist/train_contrastive.py, 
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [2], 
  launch_method: local, 
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 8, job-name: ms-train, mem-per-cpu: 12G, time: '1-18:00:00'}
  # Debug and debug overfit
  debug: [false] #debug
  seed: [1]

  labels-file: [data/paired_spectra/canopus_train/labels.tsv]
  subform-folder: [data/paired_spectra/canopus_train/subformulae/subformulae_default/]
  spec-folder: [data/paired_spectra/canopus_train/spec_files/]
  magma-folder: [data/paired_spectra/canopus_train/magma_outputs/]
  hdf-file: [data/paired_spectra/canopus_train/retrieval_hdf/intpubchem_with_morgan4096_retrieval_db_contrast.h5]

  # Data aug
  augment-data: [true]
  augment-prob: [0.5]
  remove-prob: [0.5]
  remove-weights: [exp]
  inten-prob: [0.1]

  # Contrastive loss
  contrastive-loss: [nce]
  contrastive-decoy-pool: [mean]
  contrastive-latent: [h0]
  contrastive-weight: [0.6]
  contrastive-scale: [16] 
  contrastive-bias: [0.0] 
  num-decoys: [64]
  max-db-decoys: [256]
  decoy-norm-exp: [4]
  contrastive-latent-size: [null]
  negative-strategy: [hardisomer_tani_pickled]
  dist-name: [cosine]

  learning-rate: [0.00057]
  weight-decay: [1.0e-07]
  scheduler: [True]
  lr-decay-frac: [0.7138]
  patience: [10]
  max-epochs: [500]
  gpus: [1]
  batch-size: [32]
  num-workers: [8] # 8
  persistent-workers: [false]
  cache-featurizers: [true]

iterative_args:
  - ckpt-file: [
    "results/canopus_fp_mist/split_0/canopus_hplus_100_0/best.ckpt"
    ]
    save-dir: [split_0]
    split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_100_0.tsv]

    # Forward aug
    forward-labels: [data/paired_spectra/canopus_train/aug_iceberg_canopus_train/biomols_filtered_smiles_canopus_train_labels.tsv]
    forward-aug-folder: [data/paired_spectra/canopus_train/aug_iceberg_canopus_train/canopus_hplus_100_0/subforms/]
    frac-orig: [0.2]
