launcher_args: {experiment_name: canopus_fp_ffn,
  script_name: src/mist/train_ffn_binned.py,
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [1],
  launch_method: local,
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 6, job-name: ms-train, mem-per-cpu: 10G,
    time: '1-18:00:00'}

  cache-featurizers: [true]

  labels-file: [data/paired_spectra/canopus_train/labels.tsv]
  spec-folder: [data/paired_spectra/canopus_train/spec_files/]

  # Debug
  debug: [false]
  fp-names:
  - - morgan4096
  num-workers: [16]
  persistent-workers: [false]
  seed: [1]
  gpus: [1]

  # Data params
  augment-data: [false]
  forward-labels: [null]

  # Learning
  max-epochs: [600]
  scheduler: [false]
  batch-size: [64]
  learning-rate: [8.7e-4]
  weight-decay: [1.0e-07]
  loss-fn: [cosine]

  # Model params
  hidden-size: [512]
  num-spec-layers: [2]
  num-bins: [11000]
  spectra-dropout: [0.3]
  patience: [20]
  iterative-preds: [none]

iterative_args:
  - save-dir: [split_0]
    split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_100_0.tsv]
    embed-instrument: [false]
