launcher_args: {experiment_name: canopus_fp_mist, 
script_name: src/mist/train_mist.py,
  slurm_script: launcher_scripts/generic_slurm.sh, 
  visible_devices: [0],
  launch_method: local
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 6, job-name: ms-train, mem-per-cpu: 10G, time: '1-18:00:00'}

  cache-featurizers: [true]

  labels-file: [data/paired_spectra/canopus_train/labels.tsv]
  subform-folder: [data/paired_spectra/canopus_train/subformulae/subformulae_default/]
  spec-folder: [data/paired_spectra/canopus_train/spec_files/]
  magma-folder: [data/paired_spectra/canopus_train/magma_outputs/magma_tsv/]


  # Debug
  debug: [false]
  fp-names:
  - - morgan4096
  num-workers: [16]
  persistent-workers: [false]
  seed: [1]

  gpus: [1]

  # Data augmentation
  augment-data: [true]
  augment-prob: [0.5]
  batch-size: [128]
  inten-prob: [0.1]
  remove-prob: [0.5]
  remove-weights: [exp]

  # Iterative predictions
  iterative-preds: [growing]
  iterative-loss-weight: [0.4]
  learning-rate: [0.00077]
  weight-decay: [1.0e-07]

  # Learning
  max-epochs: [600]
  scheduler: [false] 
  lr-decay-frac: [0.90]

  # Model params
  hidden-size: [256]
  num-heads: [8]
  pairwise-featurization: [true]
  peak-attn-layers: [2]
  refine-layers: [4] 
  set-pooling: [cls]
  spectra-dropout: [0.1] 
  cls-type: [ms1]
  loss-fn: [cosine]

  # Magma args
  magma-aux-loss: [true]
  magma-loss-lambda: [8]
  magma-modulo: [512]
  patience: [20]

iterative_args:
  - split-file: [data/paired_spectra/canopus_train/splits/canopus_hplus_100_0.tsv]
    save-dir: [split_0]

    # Forward aug
    forward-labels: [data/paired_spectra/canopus_train/aug_iceberg_canopus_train/biomols_filtered_smiles_canopus_train_labels.tsv]
    forward-aug-folder: [data/paired_spectra/canopus_train/aug_iceberg_canopus_train/canopus_hplus_100_0/subforms/]
    frac-orig: [0.6]

    # Reverted to original paper
    form-embedder: [pos-cos]
    embed-instrument: [false]
    no-diffs: [true]
